import "@/styles/css/index.css";
import "@/styles/sass/index.scss";
import { Inter } from "next/font/google";
import { BaseContentLayout } from "@/components/layouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <html lang="en">
      <body>
        <BaseContentLayout>{children}</BaseContentLayout>
      </body>
    </html>
  );
}
